easy_admin:
  entities:
    User:
      class: App\Entity\User
      form:
        fields:
          - { property: "email" }
          - { property: "firstname" }
          - { property: "lastname" }

      list:
        actions:
          - { name: "edit", icon: "pencil", label: false, css_class: "btn btn-primary" }
          - { name: "delete", icon: "trash", label: false, css_class: "btn btn-danger" }